// import "./globals.css";
"use client";
import { Roboto } from "next/font/google";

import { CssBaseline } from "@nextui-org/react";
import { ThemeProvider } from "@mui/material";
import { lightTheme, darkTheme } from "@/themes";

const roboto = Roboto({
	weight: ["100", "300", "400", "500"],
	style: "normal",
	subsets: ["latin"],
	display: "swap",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="es" className={roboto.className}>
			<head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</head>
			<ThemeProvider theme={darkTheme}>
				<CssBaseline />
				<body>{children}</body>
			</ThemeProvider>
		</html>
	);
}
