"use client";
import { CssBaseline, ThemeProvider } from "@mui/material";
import "./globals.css";
import { Roboto } from "next/font/google";
import { darkTheme, lightTheme } from "@/themes";
import { UIProvider } from "../context/ui/";

const roboto = Roboto({
	weight: ["100", "300", "500", "700"],
	style: "normal",
	subsets: ["latin"],
	display: "swap",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="es">
			<head>
				<link
					href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&display=swap"
					rel="stylesheet"
				/>
				<title>OpenJira</title>
			</head>
			<UIProvider>
				<ThemeProvider theme={darkTheme}>
					<CssBaseline />
					<body className={roboto.className}>{children}</body>
				</ThemeProvider>
			</UIProvider>
		</html>
	);
}
